- name: Install packages for Jenkins node
  apt:
    name:
      - openjdk-17-jdk
      - git
      - ssh
      - python3-pip
    state: present
    update_cache: yes


- name: Create jenkins user with password
  user:
    name: jenkins
    home: /home/jenkins
    shell: /bin/bash
    create_home: yes
    password: "$6$Bi/CrwdywL3At22J$ezhMigV.yuRIcfqBBCgScx9Ey/ABFETIWL9w01qMreTeRSoIpYZvXkCkCR1hPZmpEk8A2IXetLTuYrQFMjBse1"
