name: Terraform EC2 Provisioning

on:
  push:
    branches:
      - main

jobs:
  deploy_ec2:
    name: Apply Terraform EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./tenvm_proj
        run: terraform init

      - name: Terraform Validate
        working-directory: ./tenvm_proj
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./tenvm_proj
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./tenvm_proj
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: get_ip
        working-directory: ./tenvm_proj
        run: |
          echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> "$GITHUB_ENV"  

  deploy_ansible:
    name: Install Ansible on EC2
    runs-on: ubuntu-latest
    needs: deploy_ec2
    env:
      REMOTE_HOST: ${{ needs.deploy_ec2.outputs.INSTANCE_IP }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update -y && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

      - name: Install Ansible remotely
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@$REMOTE_HOST << 'EOF'
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install -y ansible
            ansible --version
          EOF
